Consultorio/Consultorio/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('registros/', include('registros.urls')),
    path('iniciosesion/', include('iniciosesion.urls')),
    path('salaespera/', include('salaespera.urls')),
    path('menucita/', include ('menucita.urls')),
    path('menuchat/', include ('menuchat.urls')),
    path('agendar/', include('agendar.urls'))

]
 

Consultorio/agendar/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', views.agendar, name="Mi primera Html"),
    path('crud/', views.crud, name="Crud"),
]

Consultorio/registros/urls.py
from django.urls import path
from django.contrib import admin
from . import views

urlpatterns = [
    path("", views.registro, name="Mi primera Html"),
    #path("eliminar/<int:usuario_id>/", views.eliminar, name=views.eliminar)
]

Consultorio/registros/models.py
from django.db import models
#from django.core.urlresolvers import reverse_lazy

# Create your models here.

class Usuario(models.Model):
    nombre = models.CharField(max_length=45, blank=True, null=True)
    apellido = models.CharField(max_length=45, blank=True, null=True)
    cedula = models.IntegerField()
    edad = models.IntegerField()
    genero = models.CharField(max_length=45, blank=True, null=True)
    correo = models.EmailField()
    telefono = models.CharField(max_length=45, blank=True, null=True)
    contraseña = models.CharField(max_length=45, blank=True, null=True)

    def __str__(self) -> str:
        return self.nombre
        

# class Resultado(models.Model):
#     medico = 
#     paciente = 
#     diagnostico = 
#     fecha = models.ForeignKey(Citas, verbose_name=_("fecha"), on_delete=models.CASCADE)
#     hora = models.ForeignKey(Citas, verbose_name=_("hora"), on_delete=models.CASCADE)
#     models.models.ForeignKey("app.Model", verbose_name=_(""), on_delete=models.CASCADE)

Consultorio/registros/forms.py
from django.forms import ModelForm
from .models import Usuario 

class UsuarioForm(ModelForm):    
    class Meta:
        model = Usuario
        fields = [
                'nombre',
                'apellido',
                'cedula',
                'edad',
                'genero',
                'telefono',
                'correo',
                ]

        

Consultorio/registros/views.py
from django.core.checks import messages
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from .forms import UsuarioForm
from .models import Usuario 

def registro(request):
    if request.method == "POST":
        form = UsuarioForm(request.POST)
        print("Entra a agendar")
        if form.is_valid():            
            creado = form.cleaned_data['nombre']
            messages.success(request, '¡Usuario registrado con exito!' )
            form.save()
            return redirect('http://localhost:8000/iniciosesion/')

    else:
        print("No es valido el post")
        form = UsuarioForm()

    context = {'form': form}
    return render(request, 'registros.html', context)

def eliminar(request, usuario_id):
    usuario = Usuario.objects.get(id=usuario_id)
    usuario.delete()
    return redirect("inicio")

Consultorio/registros/templates/elimreg.html
<!DOCTYPE html>
<html lang="es">
{% load static %}
<head>
	<meta charset="Latin1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet"href="{% static 'Css/Encabezado.css' %}">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
	<title>Registro</title>


</head>
<!--Inicio del encabezado-->

<header class="header">
		<div class="conteiner logo-nav-conteiner">
        
			<a href="#" class="logo"> <img src="{% static 'Imagenes/pokemon.gif' %}" width="100" height="100"> </a>
			<h1>CONSULTORIO VIRTUAL</h1>
			<span class="menu-icon">Ver menú</span>
			<nav class="navigation">
		<ul class="menu">

		<!--Palabras que aparecen en el menu-->
		<li>
			<a href="http://localhost:8000/iniciosesion/html/">Login</a>		
		</li>
		<!--Fin menu plegable-->	
	</ul>			
			</nav>
		</div>
	</header>
<script src="JS/jquery-slim.min.js" ></script>
<script src="JS/scripts.js" ></script>
<body bgcolor="#D8E4F7">
<!--fin del encabezado-->
<body>
    <h1>REgistradoooo</h1>

    <ul>
    {% for paciente in paciente%}
        <li>{{ paciente }} </li>
    {% endfor %}
    </ul>
</body>


			<div class="foto">
 				<img class="forma"src="{% static 'Imagenes/doctor2.png' %}">
			</div>
		</form>
{% endblock content %}
</div>


<!--Inicio del footer-->
		<footer
	class="text-center text-lg-start text-white"
	style="background-color: #1c2331"
	>
	<!-- Section: Social media -->
	<section
	class="d-flex justify-content-between p-4"
	style="background-color: #0d6efd"
	>
	<!-- Left -->
	<div class="me-5">
		<span> Tu salud en las mejores manos</span>
	</div>
	<!-- Left -->

	<!-- Right -->
	<div>
		<a href="" class="text-white me-4">
			<i class="fab fa-facebook-f"></i>
		</a>
		<a href="" class="text-white me-4">
			<i class="fab fa-twitter"></i>
		</a>
		<a href="" class="text-white me-4">
			<i class="fab fa-google"></i>
		</a>
		<a href="" class="text-white me-4">
			<i class="fab fa-instagram"></i>
		</a>
		<a href="" class="text-white me-4">
			<i class="fab fa-linkedin"></i>
		</a>
		<a href="" class="text-white me-4">
			<i class="fab fa-github"></i>
		</a>
	</div>
	<!-- Right -->
</section>
<!-- Section: Social media -->

<!-- Section: Links  -->
<section class="">
	<div class="container text-center text-md-start mt-5">
		<!-- Grid row -->
		<div class="row mt-3">
			<!-- Grid column -->
			<div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
				<!-- Content -->
				<h6 class="text-uppercase fw-bold">Consultorio Online</h6>
				<hr
				class="mb-4 mt-0 d-inline-block mx-auto"
				style="width: 60px; background-color: #7c4dff; height: 2px"
				/>
				<p> Agenda tu cita desde la comodidad de tu hogar</p>
			</div>
			<!-- Grid column -->

			<!-- Grid column -->
			<div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
				<!-- Links -->
				<h6 class="text-uppercase fw-bold">Doctores</h6>
				<hr
				class="mb-4 mt-0 d-inline-block mx-auto"
				style="width: 60px; background-color: #7c4dff; height: 2px"
				/>
				<p> 
					<a href="#!" class="text-white">Dr. Chapatin</a>
				</p>
				<p>
					<a href="#!" class="text-white"> Dra. Corazón</a>
				</p>
				<p>
					<a href="#!" class="text-white">Dr. Huesitos</a>
				</p>
				<p>
					<a href="#!" class="text-white">Dra. Angular</a>
				</p>
			</div>
			<!-- Grid column -->

			<!-- Grid column -->
			<div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
				<!-- Links -->
				<h6 class="text-uppercase fw-bold">Especialidades</h6>
				<hr
				class="mb-4 mt-0 d-inline-block mx-auto"
				style="width: 60px; background-color: #7c4dff; height: 2px"
				/>
				<p>
					<a href="#!" class="text-white">Medicina General</a>
				</p>
				<p>
					<a href="#!" class="text-white">Odontologia</a>
				</p>
				<p>
					<a href="#!" class="text-white">Internista</a>
				</p>
				<p>
					<a href="#!" class="text-white">Urgencias</a>
				</p>
			</div>
			<!-- Grid column -->

			<!-- Grid column -->
			<div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
				<!-- Links -->
				<h6 class="text-uppercase fw-bold">Contactenos</h6>
				<hr
				class="mb-4 mt-0 d-inline-block mx-auto"
				style="width: 60px; background-color: #7c4dff; height: 2px"
				/>
				<p><i class="fas fa-home mr-3"></i> Colombia</p>
				<p><i class="fas fa-envelope mr-3"></i> consultorio@gmail.com</p>
				<p><i class="fas fa-phone mr-3"></i> +57 123 456 25</p>
				<p><i class="fas fa-print mr-3"></i> + 01 234 567 89</p>
			</div>
			<!-- Grid column -->
		</div>
		<!-- Grid row -->
	</div>
</section>
<!-- Section: Links  -->

<!-- Copyright -->
<div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)"> 
	© 2020 Copyright: Grupo 2 MisionTIC
</div>
</footer>	

</body>
</html>

Consultorio/registros/templates/registros.html
<!DOCTYPE html>
<html lang="es">
{% load static %}
<head>
	<meta charset="Latin1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet"href="{% static 'Css/Encabezado.css' %}">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
	<title>Registro</title>


</head>
<!--Inicio del encabezado-->

<header class="header">
		<div class="conteiner logo-nav-conteiner">
        
			<a href="#" class="logo"> <img src="{% static 'Imagenes/pokemon.gif' %}" width="100" height="100"> </a>
			<h1>CONSULTORIO VIRTUAL</h1>
			<span class="menu-icon">Ver menú</span>
			<nav class="navigation">
		<ul class="menu">

		<!--Palabras que aparecen en el menu-->
		<li>
			<a href="http://localhost:8000/iniciosesion/">Login</a>		
		</li>
		<!--Fin menu plegable-->	
	</ul>			
			</nav>
		</div>
	</header>
<script src="JS/jquery-slim.min.js" ></script>
<script src="JS/scripts.js" ></script>
<body bgcolor="#D8E4F7">
<!--fin del encabezado-->

<div class="encabezado1">
<form class="encabezado2" method="POST" action="">{% csrf_token %}
{{ form.as_p}}		
Contraseña:<br>
<input type="password" name="contraseña" maxlength="45" id="id_contraseña">
			<input class="boton1" type="submit"  value="Registrarme" />
			<input class="boton2" type="reset" value="Borrar Formulario" />	
			<br>
			<br>

			<div class="foto">
 				<img class="forma"src="{% static 'Imagenes/doctor2.png' %}">
			</div>
		</form>
	
</div>


<!--Inicio del footer-->
		<footer
	class="text-center text-lg-start text-white"
	style="background-color: #1c2331"
	>
	<!-- Section: Social media -->
	<section
	class="d-flex justify-content-between p-4"
	style="background-color: #0d6efd"
	>
	<!-- Left -->
	<div class="me-5">
		<span> Tu salud en las mejores manos</span>
	</div>
	<!-- Left -->

	<!-- Right -->
	<div>
		<a href="" class="text-white me-4">
			<i class="fab fa-facebook-f"></i>
		</a>
		<a href="" class="text-white me-4">
			<i class="fab fa-twitter"></i>
		</a>
		<a href="" class="text-white me-4">
			<i class="fab fa-google"></i>
		</a>
		<a href="" class="text-white me-4">
			<i class="fab fa-instagram"></i>
		</a>
		<a href="" class="text-white me-4">
			<i class="fab fa-linkedin"></i>
		</a>
		<a href="" class="text-white me-4">
			<i class="fab fa-github"></i>
		</a>
	</div>
	<!-- Right -->
</section>
<!-- Section: Social media -->

<!-- Section: Links  -->
<section class="">
	<div class="container text-center text-md-start mt-5">
		<!-- Grid row -->
		<div class="row mt-3">
			<!-- Grid column -->
			<div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
				<!-- Content -->
				<h6 class="text-uppercase fw-bold">Consultorio Online</h6>
				<hr
				class="mb-4 mt-0 d-inline-block mx-auto"
				style="width: 60px; background-color: #7c4dff; height: 2px"
				/>
				<p> Agenda tu cita desde la comodidad de tu hogar</p>
			</div>
			<!-- Grid column -->

			<!-- Grid column -->
			<div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
				<!-- Links -->
				<h6 class="text-uppercase fw-bold">Doctores</h6>
				<hr
				class="mb-4 mt-0 d-inline-block mx-auto"
				style="width: 60px; background-color: #7c4dff; height: 2px"
				/>
				<p> 
					<a href="#!" class="text-white">Dr. Chapatin</a>
				</p>
				<p>
					<a href="#!" class="text-white"> Dra. Corazón</a>
				</p>
				<p>
					<a href="#!" class="text-white">Dr. Huesitos</a>
				</p>
				<p>
					<a href="#!" class="text-white">Dra. Angular</a>
				</p>
			</div>
			<!-- Grid column -->

			<!-- Grid column -->
			<div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
				<!-- Links -->
				<h6 class="text-uppercase fw-bold">Especialidades</h6>
				<hr
				class="mb-4 mt-0 d-inline-block mx-auto"
				style="width: 60px; background-color: #7c4dff; height: 2px"
				/>
				<p>
					<a href="#!" class="text-white">Medicina General</a>
				</p>
				<p>
					<a href="#!" class="text-white">Odontologia</a>
				</p>
				<p>
					<a href="#!" class="text-white">Internista</a>
				</p>
				<p>
					<a href="#!" class="text-white">Urgencias</a>
				</p>
			</div>
			<!-- Grid column -->

			<!-- Grid column -->
			<div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
				<!-- Links -->
				<h6 class="text-uppercase fw-bold">Contactenos</h6>
				<hr
				class="mb-4 mt-0 d-inline-block mx-auto"
				style="width: 60px; background-color: #7c4dff; height: 2px"
				/>
				<p><i class="fas fa-home mr-3"></i> Colombia</p>
				<p><i class="fas fa-envelope mr-3"></i> consultorio@gmail.com</p>
				<p><i class="fas fa-phone mr-3"></i> +57 123 456 25</p>
				<p><i class="fas fa-print mr-3"></i> + 01 234 567 89</p>
			</div>
			<!-- Grid column -->
		</div>
		<!-- Grid row -->
	</div>
</section>
<!-- Section: Links  -->

<!-- Copyright -->
<div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)"> 
	© 2020 Copyright: Grupo 2 MisionTIC
</div>
</footer>	

</body>
</html>