Consultorio/Consultorio/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('registros/', include('registros.urls')),
    path('iniciosesion/', include('iniciosesion.urls')),
    path('salaespera/', include('salaespera.urls')),
    path('menucita/', include ('menucita.urls')),
    path('menuchat/', include ('menuchat.urls')),
    path('agendar/', include('agendar.urls'))

]
 

Consultorio/agendar/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', views.agendar, name="Mi primera Html"),
    path('crud/', views.crud, name="Crud"),
]

Consultorio/agendar/models.py
from django.db import models

# Create your models here.
class Citas(models.Model):
    fecha = models.DateField(null=True)
    hora = models.TimeField(null=True)
    paciente = models.CharField(max_length=45, blank=True, null=True)
    cormobilidad = models.CharField(max_length=45, blank=True, null=True)
    sintomas = models.CharField(max_length=45, blank=True, null=True)
    horassintomas = models.IntegerField()

    def __str__(self) -> str:
        return self.paciente

Consultorio/agendar/forms.py
from django.forms import ModelForm
from .models import Citas

class citasForm(ModelForm):
        class Meta:
                model = Citas
                fields = [
                        'paciente',
                        'cormobilidad',
                        'sintomas',
                        'horassintomas'
                        ]
        
        
        

Consultorio/agendar/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import citasForm
from .models import Citas


def crud(request):
    return HttpResponse("Hola clase")

def miHtml(request):
    parametros=""
    return render(request, 'agendar.html')

def agendar(request):
    print("Entra a agendar")
    #variable = Citas.objects.all()
    #variable.get()
    if request.method == "POST":
        print("request.method: "+request.method)
        form = citasForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('http://localhost:8000/iniciosesion/')

    else:
        print("request: "+request.method)
        form = citasForm() 
        pass

    context = {'form': form}
    return render(request, 'agendar.html', context)

Consultorio/agendar/templates/agendar.html
<!DOCTYPE html>
<html lang="es">
{% load static %}
<head>
	<meta charset="Latin1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet"href="{% static 'css/agenda.css' %}">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
	<title>Agendar</title>
</head>
<!--Inicio del encabezado-->

<header class="header">
		<div class="conteiner logo-nav-conteiner">
        
			<a href="#" class="logo"> <img src="{% static 'Imagenes/pokemon.gif' %}" width="100" height="100"> </a>
			<h1>Consultorio virtual</h1>
			<span class="menu-icon">Ver menú</span>
			<nav class="navigation">
		<ul class="menu">

		<!--Palabras que aparecen en el menu-->
		<li><a href=""></a>
		
		</li>
		<li><a href=""></a>
		<!--Menu plegable-->
		</li>
		<li><a href="#"></a>
			<ul class="submenu">
				<li><a href=""></a></li>
				<li><a href=""></a></li>
			</ul>
		</li>
		<!--Fin menu plegable-->	
	</ul>			
			</nav>
		</div>
	</header>
<script src="JS/jquery-slim.min.js" ></script>
<script src="JS/scripts.js" ></script>
<body class="body">
{% csrf_token %}
{{ form.as_p}}		
<!--fin del encabezado-->
<div class="contenedor">
<img class="foto" src="{% static 'Imagenes/portapapeles.png' %}" />
	<div class="texto-encima">Agenda tu Cita</div>
  	    <div class="centrado">
  			<div class="encabezado1">
				<form class="encabezado2" method="POST" action="" >
								
				Seleccione el día de su cita:<br>
				<input class="prueba"type="date" name="fecha" id="id_fecha">
				<br>
				Seleccione la hora de su cita:<br>
				<input class="prueba" type="time" name="hora" id="id_hora">
				<br>
				Especialidad:<br>
				<select class="prueba">
					<option>
						Seleccione
					</option>
					<option>
						Medicina general
					</option>
					<option>
						Medicina Interna
					</option>
					<option>
						Psicologia
					</option>
					<option>
						Pediatria
					</option>
				</select><br>
				Enfermedad Base: (Opcional)<br>
				<label><input class="prueba" type="checkbox" name="apellido">Hipertensión</label>
				<br>
				<label><input class="prueba" type="checkbox" name="apellido">Obesidad</label>
				<br>
				<label><input class="prueba" type="checkbox" name="cormobilidad" id="id_cormobilidad">Diabetes</label>
				<br>
				<label><input class="prueba" type="checkbox" name="apellido">Otros</label>
				<br>
				Sintomas:<br>
				<input class="prueba" placeholder="Escriba sus sintomas aquí" type="text" >
				<br>
				Hace cuánto los tiene:<br>
				<select class="prueba">
					<option>
						Seleccione
					</option>
					<option>
						1 - 2 días
					</option>
					<option>
						3 - 5 días
					</option>
					<option>
						6 - 10 días
					</option>
					<option>
						11 - 15 días
					</option>
				</select><br>
					<br>
					<input class="boton1" type="submit"  value="Enviar Solicitud" >
					<input class="boton2" type="reset" value="Borrar">
					<p><a class="boton1" href="http://localhost:8000/menucita/">Cancelar</a></p>
					
				</form>
	
			</div>
    	</div>
	</div>
	
</div>
<!--Inicio del footer-->
		<footer
	class="text-center text-lg-start text-white"
	style="background-color: #1c2331"
	>
	<!-- Section: Social media -->
	<section
	class="d-flex justify-content-between p-4"
	style="background-color: #0d6efd"
	>
	<!-- Left -->
	<div class="me-5">
		<span> Tu salud en las mejores manos</span>
	</div>
	<!-- Left -->

	<!-- Right -->
	<div>
		<a href="" class="text-white me-4">
			<i class="fab fa-facebook-f"></i>
		</a>
		<a href="" class="text-white me-4">
			<i class="fab fa-twitter"></i>
		</a>
		<a href="" class="text-white me-4">
			<i class="fab fa-google"></i>
		</a>
		<a href="" class="text-white me-4">
			<i class="fab fa-instagram"></i>
		</a>
		<a href="" class="text-white me-4">
			<i class="fab fa-linkedin"></i>
		</a>
		<a href="" class="text-white me-4">
			<i class="fab fa-github"></i>
		</a>
	</div>
	<!-- Right -->
</section>
<!-- Section: Social media -->

<!-- Section: Links  -->
<section class="">
	<div class="container text-center text-md-start mt-5">
		<!-- Grid row -->
		<div class="row mt-3">
			<!-- Grid column -->
			<div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
				<!-- Content -->
				<h6 class="text-uppercase fw-bold">Consultorio Online</h6>
				<hr
				class="mb-4 mt-0 d-inline-block mx-auto"
				style="width: 60px; background-color: #7c4dff; height: 2px"
				/>
				<p> Agenda tu cita desde la comodidad de tu hogar</p>
			</div>
			<!-- Grid column -->

			<!-- Grid column -->
			<div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
				<!-- Links -->
				<h6 class="text-uppercase fw-bold">Doctores</h6>
				<hr
				class="mb-4 mt-0 d-inline-block mx-auto"
				style="width: 60px; background-color: #7c4dff; height: 2px"
				/>
				<p> 
					<a href="#!" class="text-white">Dr. Chapatin</a>
				</p>
				<p>
					<a href="#!" class="text-white"> Dra. Corazón</a>
				</p>
				<p>
					<a href="#!" class="text-white">Dr. Huesitos</a>
				</p>
				<p>
					<a href="#!" class="text-white">Dra. Angular</a>
				</p>
			</div>
			<!-- Grid column -->

			<!-- Grid column -->
			<div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
				<!-- Links -->
				<h6 class="text-uppercase fw-bold">Especialidades</h6>
				<hr
				class="mb-4 mt-0 d-inline-block mx-auto"
				style="width: 60px; background-color: #7c4dff; height: 2px"
				/>
				<p>
					<a href="#!" class="text-white">Medicina General</a>
				</p>
				<p>
					<a href="#!" class="text-white">Odontologia</a>
				</p>
				<p>
					<a href="#!" class="text-white">Internista</a>
				</p>
				<p>
					<a href="#!" class="text-white">Urgencias</a>
				</p>
			</div>
			<!-- Grid column -->

			<!-- Grid column -->
			<div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
				<!-- Links -->
				<h6 class="text-uppercase fw-bold">Contactenos</h6>
				<hr
				class="mb-4 mt-0 d-inline-block mx-auto"
				style="width: 60px; background-color: #7c4dff; height: 2px"
				/>
				<p><i class="fas fa-home mr-3"></i> Colombia</p>
				<p><i class="fas fa-envelope mr-3"></i> consultorio@gmail.com</p>
				<p><i class="fas fa-phone mr-3"></i> +57 123 456 25</p>
				<p><i class="fas fa-print mr-3"></i> + 01 234 567 89</p>
			</div>
			<!-- Grid column -->
		</div>
		<!-- Grid row -->
	</div>
</section>
<!-- Section: Links  -->

<!-- Copyright -->
<div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)"> 
	© 2020 Copyright: Grupo 2 MisionTIC
</div>
</footer>	

</body>
</html>